language: python
services:
  - docker

before_install:
  - docker pull python:3.10
  - docker run -v $PWD:/app -w /app python:3.10 sh -c "pip install poetry && poetry install"

script:
  - docker run -v $PWD:/app -w /app python:3.10 sh -c "poetry run pytest"